# Generated by Django 4.1.7 on 2023-04-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(default='America/Chicago', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time_local', models.TimeField(default='00:00:00')),
                ('end_time_local', models.TimeField(default='23:59:59')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantMonitoring.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=8)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantMonitoring.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_last_hour', models.IntegerField()),
                ('uptime_last_day', models.IntegerField()),
                ('uptime_last_week', models.IntegerField()),
                ('downtime_last_hour', models.IntegerField()),
                ('downtime_last_day', models.IntegerField()),
                ('downtime_last_week', models.IntegerField()),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantMonitoring.restaurant')),
            ],
        ),
    ]
