# Generated by Django 4.1.7 on 2023-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMonitoring', '0003_populate_restaurant_timings_data'),
    ]

    operations = [
    ]
