# Generated by Django 4.1.7 on 2023-04-04 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMonitoring', '0004_populate_restaurant_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstatus',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurantstatus',
            name='timestamp_utc',
            field=models.CharField(default='2023-01-25 18:13:22.47922 UTC', max_length=100),
        ),
    ]
