# Generated by Django 4.1.7 on 2023-04-04 18:32

import RestaurantMonitoring.commons
import datetime
from django.db import migrations
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMonitoring', '0005_restaurantstatus_time_created_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=functools.partial(RestaurantMonitoring.commons.populate_restaurant_status, *(), **{'time_created': datetime.datetime(2023, 4, 4, 18, 32, 1, 30586, tzinfo=datetime.timezone.utc)}),
            reverse_code=functools.partial(RestaurantMonitoring.commons.reverse_migrate, *(), **{'time_created': datetime.datetime(2023, 4, 4, 18, 32, 1, 30586, tzinfo=datetime.timezone.utc)}),
        ),
    ]
